services:
  web:
    build: .
    container_name: movielibrary_app
    command: uvicorn movielibrary.main:app --host 0.0.0.0 --port 8000
    volumes:
      - .:/app
    ports:
      - "127.0.0.1:8002:8000"
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    env_file: .env

  db:
    image: postgres:18
    container_name: filmsdb
    env_file: .env
    volumes:
      - postgres_data:/var/lib/postgresql
      - ./backup:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 2s
      timeout: 3s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: movielibrary_redis
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 2s
      timeout: 3s
      retries: 5

  # bot:
  #   build:
  #     context: ./telegrambot
  #   container_name: movielibrary_bot
  #   env_file: .env
  #   restart: always

volumes:
  postgres_data:
